### ISSUE TITLE
Why is this make program unable to read GNUMakefiles

### ISSUE THREAD

**Issue by hmaarrfk** [Archiconda/make-make-feedstock#1]
So I've been trying to recompile make......

https://app.shippable.com/github/Archiconda/make-make-feedstock/dashboard/jobs

But it is really going nowhere.

It passes the self test (you can try to re-enable them if you wish) but at the end of the day, it isn't able to compile m4.

@mingwandroid @jjhelmus is there something I am doing wrong?

shippable isn't able to boot off centos, but if you think that is the issue, I can try compiling it on qemu ....

As it is now, the CI builds make, then tries to build m4. make passes, but the m4 build, that uses the newly built `make` fails.

**Comment by jjhelmus** [comment]
Prefix replacement in make's binaries causes issues. Disabling the replacement, as is done in #2, should fix the issue. I ran into similar issue with linux-ppc64le do not recall the full details.
